---
name: Froody
version: 42.011
author:
  - |-
    You can reach the current maintainers by emailing us at C<cpan@fotango.com>,
    but if you're reporting bugs I<please> use the RT system mentioned above so
    we can track the issues you report.
abstract: Yet another XML web API framework
license: perl
requires:
  Class::Accessor::Chained::Fast: 0
  Class::Data::Inheritable: 0
  Email::Valid: 0
  Error: 0.15
  File::Spec: 0
  HTTP::Date: 0
  HTTP::Request::Common: 0
  HTTP::Server::Simple: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Module::Pluggable: 0
  Params::Validate: 0
  Template: 0
  UNIVERSAL::require: 0
  URI: 0
  XML::LibXML: 0
  YAML::Syck: 0
  perl: 5.008
recommends:
  Apache: 0
  Apache::Constants: 0
  Apache::Cookie: 0
  Apache::Request: 0
  File::Find::Rule: 0
  Logger: 0
  PPI: 0
  Test::Logger: 0
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  Test::XML: 0
provides:
  Froody:
    file: lib/Froody.pm
    version: 42.011
  Froody::API:
    file: lib/Froody/API.pm
  Froody::API::Reflection:
    file: lib/Froody/API/Reflection.pm
  Froody::API::XML:
    file: lib/Froody/API/XML.pm
  Froody::Argument:
    file: lib/Froody/Argument.pm
  Froody::Argument::CSV:
    file: lib/Froody/Argument/CSV.pm
  Froody::Argument::Email:
    file: lib/Froody/Argument/Email.pm
  Froody::Argument::Multipart:
    file: lib/Froody/Argument/Multipart.pm
  Froody::Argument::Number:
    file: lib/Froody/Argument/Number.pm
  Froody::Argument::Text:
    file: lib/Froody/Argument/Text.pm
  Froody::Argument::Trim:
    file: lib/Froody/Argument/Trim.pm
  Froody::Base:
    file: lib/Froody/Base.pm
  Froody::Dispatch:
    file: lib/Froody/Dispatch.pm
  Froody::DocServer:
    file: lib/Froody/DocServer.pm
  Froody::Error:
    file: lib/Froody/Error.pm
  Froody::ErrorType:
    file: lib/Froody/ErrorType.pm
    version: 0.01
  Froody::Implementation:
    file: lib/Froody/Implementation.pm
    version: 0.01
  Froody::Invoker:
    file: lib/Froody/Invoker.pm
    version: 0.01
  Froody::Invoker::Implementation:
    file: lib/Froody/Invoker/Implementation.pm
  Froody::Invoker::PluginService:
    file: lib/Froody/Invoker/PluginService.pm
  Froody::Invoker::Remote:
    file: lib/Froody/Invoker/Remote.pm
    version: 0.01
  Froody::Logger:
    file: lib/Froody/Logger.pm
  Froody::Logger::Compat:
    file: lib/Froody/Logger.pm
  Froody::Method:
    file: lib/Froody/Method.pm
    version: 0.01
  Froody::Plugin:
    file: lib/Froody/Plugin.pm
  Froody::Pod:
    file: lib/Froody/Pod.pm
  Froody::Reflection:
    file: lib/Froody/Reflection.pm
  Froody::Renderer::json:
    file: lib/Froody/Renderer/json.pm
  Froody::Repository:
    file: lib/Froody/Repository.pm
    version: 0.01
  Froody::Request:
    file: lib/Froody/Request.pm
  Froody::Request::Apache:
    file: lib/Froody/Request/Apache.pm
  Froody::Request::CGI:
    file: lib/Froody/Request/CGI.pm
  Froody::Response:
    file: lib/Froody/Response.pm
  Froody::Response::Content:
    file: lib/Froody/Response/Content.pm
    version: 0.01
  Froody::Response::Error:
    file: lib/Froody/Response/Error.pm
  Froody::Response::PerlDS:
    file: lib/Froody/Response/PerlDS.pm
  Froody::Response::String:
    file: lib/Froody/Response/String.pm
  Froody::Response::Terse:
    file: lib/Froody/Response/Terse.pm
  Froody::Response::XML:
    file: lib/Froody/Response/XML.pm
  Froody::Server:
    file: lib/Froody/Server.pm
  Froody::Server::Apache:
    file: lib/Froody/Server/Apache.pm
  Froody::Server::CGI:
    file: lib/Froody/Server/CGI.pm
  Froody::Server::Standalone:
    file: lib/Froody/Server/Standalone.pm
  Froody::Server::Test:
    file: lib/Froody/Server/Test.pm
  Froody::SimpleClient:
    file: lib/Froody/SimpleClient.pm
  Froody::Structure:
    file: lib/Froody/Structure.pm
    version: 0.01
  Froody::Upload:
    file: lib/Froody/Upload.pm
  Froody::Walker:
    file: lib/Froody/Walker.pm
  Froody::Walker::Driver:
    file: lib/Froody/Walker/Driver.pm
  Froody::Walker::Terse:
    file: lib/Froody/Walker/Terse.pm
  Froody::Walker::XML:
    file: lib/Froody/Walker/XML.pm
generated_by: Module::Build version 0.2609
